language: java
java:
  - 1.8
jdk:
  - oraclejdk8

before_install:
  - wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
  - unzip sonar-runner-dist-2.4.zip

branches: 
  only: 
    - master
    - desenvolvimento

addons:
  sonarqube: true

before_script:
 - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

script:
  - cd DRAS/
  - mvn clean install sonar:sonar

  
notifications:
  - slack: dras:ROSUqZH9Sz4dNJSZMoQzP9Sh
